package cn.piflow.conf

object StopGroup {

  val CommonGroup = "Common"
  val CsvGroup = "CSV"
  val HiveGroup = "Hive"
  val JdbcGroup = "Jdbc"
  val JsonGroup = "Json"
  val XmlGroup = "Xml"
  val HttpGroup = "Http"
  val FtpGroup = "Ftp"
  val ScriptGroup = "Script"
  val FileGroup = "File"
  val CleanGroup = "Data Clean"
  val KafkaGroup = "Message Queue"
  val RedisGroup = "Redis"
  val SolrGroup = "Solr"
  val ESGroup = "ElasticSearch"
  val MLGroup = "Mechine Learning"
  val RDFGroup = "RDF"
  val HdfsGroup = "Hdfs"
  val MicroorganismGroup = "Microorganism"
  val Spider = "Spider"
  val Mongodb = "MongoDB"
  val Memcache = "Memcache"
  val GraphX = "GraphX"
  val ExcelGroup = "Excel"
  val HbaseGroup = "Hbase"
  val StreamingGroup = "Streaming"
  val Neo4jGroup = "Neo4j"
  val Impala = "Impala"
}
