package cn.piflow.conf

object StopGroup {

  val CommonGroup = "Common"
  val CsvGroup = "CSV"
  val HiveGroup = "Hive"
  val JdbcGroup = "Jdbc"
  val JsonGroup = "Json"
  val XmlGroup = "Xml"
  val HttpGroup = "Http"
  val FtpGroup = "Ftp"
  val ScriptGroup = "Script"
  val FileGroup = "File"
  val CleanGroup = "Data Clean"
  val KafkaGroup = "Message Queue"
  val RedisGroup = "Redis"
  val SolrGroup = "Solr"
  val ESGroup = "ElasticSearch"
  val HdfsGroup = "Hdfs"
  val MicroorganismGroup = "BioInformatics"
  val Spider = "Spider"
  val Mongodb = "MongoDB"
  val Memcache = "Memcached"
  val GraphX = "GraphX"
  val ExcelGroup = "Excel"
  val HbaseGroup = "Hbase"
  val StreamingGroup = "Streaming"
  val Alg_NLPGroup = "Algorithms_NLP"
  val Alg_ImageProcessGroup = "Algorithms_ImageProcess"
  val Alg_ASRGroup = "Algorithms_ASR"

  val Neo4jGroup = "Algorithms_Neo4j"
  val RDFGroup = "Algorithms_RDF"

  val Algorithms_FunctionalDomain="Algorithms_FunctionalDomain"
  val Algorithms_Genome="Algorithms_Genome"
  val Algorithms_OntologyAnnotations="Algorithms_OntologyAnnotations"
  val Algorithms_Sequence="Algorithms_Sequence"
  val Algorithms_Literature="Algorithms_Literature"

  val Alg_MLCluster = "Algorithms_MachineLearningCluster"
  val MLGroup = "Algorithms_MachineLearningClassification"
  val Alg_MLFeature = "Algorithms_MachineLearningFeature"
}
