from __future__ import annotations


class RunStatus:
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"


class RunEvent:
    FLOW_SUBMITTED = "FLOW_SUBMITTED"
    FLOW_STARTED = "FLOW_STARTED"
    FLOW_COMPLETED = "FLOW_COMPLETED"
    FLOW_FAILED = "FLOW_FAILED"
    FLOW_ABORTED = "FLOW_ABORTED"

    STOP_INITIALIZED = "STOP_INITIALIZED"
    STOP_STARTED = "STOP_STARTED"
    STOP_COMPLETED = "STOP_COMPLETED"
    STOP_FAILED = "STOP_FAILED"
    STOP_SKIPPED = "STOP_SKIPPED"
