# Chemical runtime node configuration.
main_node:
  ip: 10.0.87.111
  port: 50061

nodes:
  - name: chemical-node-1
    ip: 10.0.87.111
    port: 50061
    software:
      - gaussian
      - multiwfn
  - name: chemical-node-2
    ip: 10.0.87.112
    port: 50061
    software:
      - gaussian
  - name: chemical-node-3
    ip: 10.0.87.113
    port: 50061
    software:
      - openbabel
