package cn.piflow.conf

object StopGroup {
  val NSFC = "NSFC"
  val CommonGroup = "Common"
  val CsvGroup = "CSV"
  val HiveGroup = "Hive"
  val JdbcGroup = "Jdbc"
  val JsonGroup = "Json"
  val XmlGroup = "Xml"
  val HttpGroup = "Http"
  val FtpGroup = "Ftp"
  val ScriptGroup = "Script"
  val FileGroup = "File"
  val CleanGroup = "Data Clean"
  val KafkaGroup = "Message Queue"
  val RedisGroup = "Redis"
  val SolrGroup = "Solr"
  val ESGroup = "ElasticSearch"
  val MLGroup = "Machine Learning"
  val RDFGroup = "RDF"
  val HdfsGroup = "Hdfs"
  val MicroorganismGroup = "BioInformatics"
  val Spider = "Spider"
  val Mongodb = "MongoDB"
  val Memcache = "Memcached"
  val GraphX = "GraphX"
  val ExcelGroup = "Excel"
  val HbaseGroup = "Hbase"
  val StreamingGroup = "Streaming"
  val Neo4jGroup = "Neo4j"
  val Alg_NLPGroup = "Algorithms_NLP"
  val Alg_ImageProcessGroup = "Algorithms_ImageProcess"
  val Alg_ASRGroup = "Algorithms_ASR"
  val Python = "Python"
  val Visualization = "Visualization"
  val CephGroup="ceph"
  val NormalizationGroup = "Normalization"
}
