# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import remote_execution_pb2 as remote__execution__pb2
except ImportError:  # pragma: no cover - compatibility for direct script execution
    import remote_execution_pb2 as remote__execution__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in remote_execution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemoteExecutionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitDag = channel.unary_unary(
                '/piflow.remote.RemoteExecutionService/SubmitDag',
                request_serializer=remote__execution__pb2.SubmitDagRequest.SerializeToString,
                response_deserializer=remote__execution__pb2.SubmitDagResponse.FromString,
                _registered_method=True)
        self.GetRunStatus = channel.unary_unary(
                '/piflow.remote.RemoteExecutionService/GetRunStatus',
                request_serializer=remote__execution__pb2.GetRunStatusRequest.SerializeToString,
                response_deserializer=remote__execution__pb2.GetRunStatusResponse.FromString,
                _registered_method=True)
        self.GetServerResource = channel.unary_unary(
                '/piflow.remote.RemoteExecutionService/GetServerResource',
                request_serializer=remote__execution__pb2.GetServerResourceRequest.SerializeToString,
                response_deserializer=remote__execution__pb2.GetServerResourceResponse.FromString,
                _registered_method=True)
        self.GetRunResultMeta = channel.unary_unary(
                '/piflow.remote.RemoteExecutionService/GetRunResultMeta',
                request_serializer=remote__execution__pb2.GetRunResultMetaRequest.SerializeToString,
                response_deserializer=remote__execution__pb2.GetRunResultMetaResponse.FromString,
                _registered_method=True)
        self.DownloadResult = channel.unary_stream(
                '/piflow.remote.RemoteExecutionService/DownloadResult',
                request_serializer=remote__execution__pb2.DownloadResultRequest.SerializeToString,
                response_deserializer=remote__execution__pb2.DownloadResultChunk.FromString,
                _registered_method=True)


class RemoteExecutionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SubmitDag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunResultMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitDag': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitDag,
                    request_deserializer=remote__execution__pb2.SubmitDagRequest.FromString,
                    response_serializer=remote__execution__pb2.SubmitDagResponse.SerializeToString,
            ),
            'GetRunStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunStatus,
                    request_deserializer=remote__execution__pb2.GetRunStatusRequest.FromString,
                    response_serializer=remote__execution__pb2.GetRunStatusResponse.SerializeToString,
            ),
            'GetServerResource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResource,
                    request_deserializer=remote__execution__pb2.GetServerResourceRequest.FromString,
                    response_serializer=remote__execution__pb2.GetServerResourceResponse.SerializeToString,
            ),
            'GetRunResultMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunResultMeta,
                    request_deserializer=remote__execution__pb2.GetRunResultMetaRequest.FromString,
                    response_serializer=remote__execution__pb2.GetRunResultMetaResponse.SerializeToString,
            ),
            'DownloadResult': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadResult,
                    request_deserializer=remote__execution__pb2.DownloadResultRequest.FromString,
                    response_serializer=remote__execution__pb2.DownloadResultChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'piflow.remote.RemoteExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('piflow.remote.RemoteExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteExecutionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitDag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/piflow.remote.RemoteExecutionService/SubmitDag',
            remote__execution__pb2.SubmitDagRequest.SerializeToString,
            remote__execution__pb2.SubmitDagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/piflow.remote.RemoteExecutionService/GetRunStatus',
            remote__execution__pb2.GetRunStatusRequest.SerializeToString,
            remote__execution__pb2.GetRunStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/piflow.remote.RemoteExecutionService/GetServerResource',
            remote__execution__pb2.GetServerResourceRequest.SerializeToString,
            remote__execution__pb2.GetServerResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunResultMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/piflow.remote.RemoteExecutionService/GetRunResultMeta',
            remote__execution__pb2.GetRunResultMetaRequest.SerializeToString,
            remote__execution__pb2.GetRunResultMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/piflow.remote.RemoteExecutionService/DownloadResult',
            remote__execution__pb2.DownloadResultRequest.SerializeToString,
            remote__execution__pb2.DownloadResultChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
