#llm:
#  provider: dashscope
#  model: qwen3-max
#  temperature: 0

#llm:
#  provider: dashscope
#  model: qwen3.5-plus
#  temperature: 0

#llm:
#  provider: dashscope
#  model: qwen-plus
#  temperature: 0


#llm:
#  provider: openai
#  model: glm-4.7-flash
#  temperature: 0

llm:
  provider: cstcloud
  model: qwen3.5
  temperature: 0

providers:
  dashscope:
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    api_key_env: DASHSCOPE_API_KEY

  cstcloud:
    base_url: https://uni-api.cstcloud.cn/v1
    api_key_env: CSTCLOUD_API_KEY

  openai:
    base_url: https://open.bigmodel.cn/api/paas/v4
    api_key_env: GLM_API_KEY