#!/usr/bin/env python3
"""PDF文档创建工具 - 使用reportlab从零生成PDF"""

import argparse
import json
import os

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)
from reportlab.lib import colors


def create_pdf(output_path, title=None, pagesize='letter', author=None, content=None):
    page_size = {'letter': letter, 'a4': A4}.get(pagesize, letter)
    doc = SimpleDocTemplate(output_path, pagesize=page_size)
    styles = getSampleStyleSheet()
    story = []

    if author:
        doc.author = author
    if title:
        doc.title = title

    if content:
        for item in content:
            item_type = item.get('type', 'paragraph')
            if item_type == 'title':
                story.append(Paragraph(item['text'], styles['Title']))
                story.append(Spacer(1, 12))
            elif item_type == 'heading1':
                story.append(Paragraph(item['text'], styles['Heading1']))
                story.append(Spacer(1, 8))
            elif item_type == 'heading2':
                story.append(Paragraph(item['text'], styles['Heading2']))
                story.append(Spacer(1, 6))
            elif item_type == 'paragraph':
                story.append(Paragraph(item['text'], styles['Normal']))
                story.append(Spacer(1, 6))
            elif item_type == 'spacer':
                story.append(Spacer(1, item.get('height', 12)))
            elif item_type == 'page_break':
                story.append(PageBreak())
            elif item_type == 'table':
                data = item['data']
                style_specs = []
                for s in item.get('style', []):
                    cmd = s.copy()
                    start = tuple(cmd.pop('start', (0, 0)))
                    end = tuple(cmd.pop('end', (-1, -1)))
                    name = cmd.pop('name')
                    for k, v in cmd.items():
                        if k == 'color' and isinstance(v, str):
                            cmd[k] = _parse_color(v)
                    style_specs.append((name, start, end, cmd))
                table = Table(data)
                if style_specs:
                    table.setStyle(TableStyle(style_specs))
                story.append(table)
                story.append(Spacer(1, 8))
    else:
        if title:
            story.append(Paragraph(title, styles['Title']))
            story.append(Spacer(1, 12))
        story.append(Paragraph("Generated by pdf_create skill", styles['Normal']))

    doc.build(story)
    print(f"Created PDF -> {output_path}")
    if title:
        print(f"  Title: {title}")
    print(f"  Pagesize: {pagesize}")
    print(f"  Elements: {len(content) if content else 0}")
    return output_path


def _parse_color(hex_color):
    hex_color = hex_color.lstrip('#')
    r = int(hex_color[0:2], 16) / 255
    g = int(hex_color[2:4], 16) / 255
    b = int(hex_color[4:6], 16) / 255
    return colors.Color(r, g, b)


def main():
    parser = argparse.ArgumentParser(description='PDF文档创建工具')
    parser.add_argument('--output_path', required=True, help='输出PDF文件路径')
    parser.add_argument('--title', help='文档标题')
    parser.add_argument('--pagesize', default='letter',
                        choices=['letter', 'a4'], help='页面大小')
    parser.add_argument('--author', help='作者名称')
    parser.add_argument('--content', help='内容JSON字符串，定义文档结构')

    args = parser.parse_args()
    content = None
    if args.content:
        try:
            if os.path.exists(args.content):
                with open(args.content, 'r', encoding='utf-8') as f:
                    content = json.load(f)
            else:
                content = json.loads(args.content)
        except (json.JSONDecodeError, Exception) as e:
            print(f"Warning: failed to parse content: {e}")

    os.makedirs(os.path.dirname(args.output_path) or '.', exist_ok=True)
    create_pdf(args.output_path, args.title, args.pagesize, args.author, content)


if __name__ == '__main__':
    main()
