#!/usr/bin/env python3
"""
Gaussian gjf file editor.
Supports adding Link 0 directives, route keywords, charge and multiplicity to gjf files.
Can also create new gjf files from scratch if no input file is provided.
"""

import argparse
import re
import sys
import json
from pathlib import Path

CHARGE_MULT_RE = re.compile(r"^\s*(-?\d+)\s+(\d+)(?:\s+.*)?$")


def normalize_lines(text: str) -> list[str]:
    return text.replace("\r\n", "\n").replace("\r", "\n").split("\n")


def find_route(lines: list[str]) -> tuple[int, int]:
    start = None
    for idx, line in enumerate(lines):
        stripped = line.lstrip()
        if stripped.startswith("#"):
            start = idx
            break
    if start is None:
        raise ValueError("No Gaussian route line found. Expected a line starting with '#'.")

    end = start + 1
    while end < len(lines) and lines[end].strip():
        end += 1
    return start, end


def find_charge_multiplicity(lines: list[str], start: int) -> int:
    for idx in range(start, len(lines)):
        if CHARGE_MULT_RE.match(lines[idx]):
            return idx
    raise ValueError("No charge/multiplicity line found, e.g. '0 1'.")


def route_text(raw_keywords: str) -> str:
    keywords = raw_keywords.strip()
    if not keywords:
        raise ValueError("--keywords cannot be empty.")
    if keywords.startswith("#"):
        return keywords
    return f"#p {keywords}"


def build_gjf(
    input_text: str | None,
    *,
    chk: str,
    oldchk: str | None,
    nprocshared: int,
    mem: str,
    keywords: str,
    charge: int,
    multiplicity: int,
    title: str | None,
) -> str:
    if input_text:
        lines = normalize_lines(input_text)
        route_start, route_end = find_route(lines)
        charge_idx = find_charge_multiplicity(lines, route_end)

        title_lines = [line for line in lines[route_end + 1 : charge_idx] if line.strip()]
        final_title = title if title is not None else (" ".join(title_lines).strip() or "Generated Gaussian input")

        coord_lines: list[str] = []
        idx = charge_idx + 1
        while idx < len(lines):
            line = lines[idx]
            if not line.strip():
                break
            coord_lines.append(line.rstrip())
            idx += 1

        tail_lines = [line.rstrip() for line in lines[idx + 1 :] if line.strip()]
    else:
        final_title = title if title is not None else "Generated Gaussian input"
        coord_lines = []
        tail_lines = []

    output_lines = []

    if oldchk:
        output_lines.append(f"%oldchk={oldchk}")
    output_lines.append(f"%chk={chk}")
    output_lines.append(f"%nprocshared={nprocshared}")
    output_lines.append(f"%mem={mem}")
    output_lines.append(route_text(keywords))
    output_lines.append("")
    output_lines.append(final_title)
    output_lines.append("")
    output_lines.append(f"{charge} {multiplicity}")

    if coord_lines:
        output_lines.extend(coord_lines)
    output_lines.append("")

    if tail_lines:
        output_lines.extend(tail_lines)
        output_lines.append("")

    return "\n".join(output_lines).rstrip("\n") + "\n\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fill OpenBabel-generated Gaussian gjf with Link 0 directives, route keywords, charge and multiplicity."
    )
    parser.add_argument("--input_path", help="Input gjf generated by OpenBabel. If omitted, create new gjf file.")
    parser.add_argument("--output_path", required=True, help="Output gjf path.")
    parser.add_argument("--chk", required=True, help="Gaussian checkpoint filename, e.g. acetic_opt.chk.")
    parser.add_argument("--oldchk", help="Previous checkpoint filename for restart, e.g. acetic_opt.chk.")
    parser.add_argument("--nprocshared", "--nprocshare", type=int, default=16, help="CPU cores for %%nprocshared.")
    parser.add_argument("--mem", default="8GB", help="Gaussian memory setting, e.g. 8GB.")
    parser.add_argument("--keywords", required=True, help="Gaussian route keywords, with or without leading #p.")
    parser.add_argument("--charge", type=int, default=0, help="Total molecular charge.")
    parser.add_argument("--multiplicity", type=int, default=1, help="Spin multiplicity.")
    parser.add_argument("--title", default="Acetic acid opt freq", help="Gaussian title line.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_path = Path(args.output_path)

    input_text = None
    if args.input_path:
        input_path = Path(args.input_path)
        if not input_path.exists():
            error_output = {
                "status": "failed",
                "output_path": "",
                "errorMessage": f"Input file not found: {args.input_path}"
            }
            print(json.dumps(error_output, ensure_ascii=False))
            sys.exit(1)
        input_text = input_path.read_text(encoding="utf-8")

    try:
        output_text = build_gjf(
            input_text,
            chk=args.chk,
            oldchk=args.oldchk,
            nprocshared=args.nprocshared,
            mem=args.mem,
            keywords=args.keywords,
            charge=args.charge,
            multiplicity=args.multiplicity,
            title=args.title,
        )
    except ValueError as e:
        error_output = {
            "status": "failed",
            "output_path": "",
            "errorMessage": str(e)
        }
        print(json.dumps(error_output, ensure_ascii=False))
        sys.exit(1)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output_text, encoding="utf-8", newline="\n")

    success_output = {
        "status": "success",
        "output_path": str(output_path)
    }
    print(json.dumps(success_output, ensure_ascii=False))


if __name__ == "__main__":
    main()