
package com.cscd.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-14T15:48:20.165+08:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "CscdServiceException", targetNamespace = "http://webservice.cscd.com")
public class CscdServiceException_Exception extends java.lang.Exception {

    private CscdServiceException cscdServiceException;

    public CscdServiceException_Exception() {
        super();
    }

    public CscdServiceException_Exception(String message) {
        super(message);
    }

    public CscdServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CscdServiceException_Exception(String message, CscdServiceException cscdServiceException) {
        super(message);
        this.cscdServiceException = cscdServiceException;
    }

    public CscdServiceException_Exception(String message, CscdServiceException cscdServiceException, Throwable cause) {
        super(message, cause);
        this.cscdServiceException = cscdServiceException;
    }

    public CscdServiceException getFaultInfo() {
        return this.cscdServiceException;
    }
}
