package com.cscd.webservice;

import javax.jws.*;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.io.Serializable;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-09-14T15:48:20.170+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://webservice.cscd.com", name = "CscdServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CscdServicePortType extends Serializable {

    @WebMethod(action = "urn:searchByExpr")
    @Action(input = "urn:searchByExpr", output = "urn:searchByExprResponse")
    @RequestWrapper(localName = "searchByExpr", targetNamespace = "http://webservice.cscd.com", className = "com.cscd.webservice.SearchByExpr")
    @ResponseWrapper(localName = "searchByExprResponse", targetNamespace = "http://webservice.cscd.com", className = "com.cscd.webservice.SearchByExprResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.cscd.com")
    public String searchByExpr(
            @WebParam(name = "code", targetNamespace = "http://webservice.cscd.com")
                    String code,
            @WebParam(name = "expr", targetNamespace = "http://webservice.cscd.com")
                    String expr
    );

    @WebMethod(action = "urn:searchArticles")
    @Action(input = "urn:searchArticles", output = "urn:searchArticlesResponse")
    @RequestWrapper(localName = "searchArticles", targetNamespace = "http://webservice.cscd.com", className = "com.cscd.webservice.SearchArticles")
    @ResponseWrapper(localName = "searchArticlesResponse", targetNamespace = "http://webservice.cscd.com", className = "com.cscd.webservice.SearchArticlesResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.cscd.com")
    public String searchArticles(
            @WebParam(name = "code", targetNamespace = "http://webservice.cscd.com")
                    String code,
            @WebParam(name = "author", targetNamespace = "http://webservice.cscd.com")
                    String author,
            @WebParam(name = "institute", targetNamespace = "http://webservice.cscd.com")
                    String institute,
            @WebParam(name = "title", targetNamespace = "http://webservice.cscd.com")
                    String title,
            @WebParam(name = "orcId", targetNamespace = "http://webservice.cscd.com")
                    String orcId
    );

    @WebMethod(action = "urn:getCode")
    @Action(input = "urn:getCode", output = "urn:getCodeResponse")
    @RequestWrapper(localName = "getCode", targetNamespace = "http://webservice.cscd.com", className = "com.cscd.webservice.GetCode")
    @ResponseWrapper(localName = "getCodeResponse", targetNamespace = "http://webservice.cscd.com", className = "com.cscd.webservice.GetCodeResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.cscd.com")
    public String getCode(
            @WebParam(name = "user", targetNamespace = "http://webservice.cscd.com")
                    String user,
            @WebParam(name = "passwd", targetNamespace = "http://webservice.cscd.com")
                    String passwd
    );

    @WebMethod(action = "urn:releaseCode")
    @Action(input = "urn:releaseCode")
    @Oneway
    @RequestWrapper(localName = "releaseCode", targetNamespace = "http://webservice.cscd.com", className = "com.cscd.webservice.ReleaseCode")
    public void releaseCode(
            @WebParam(name = "code", targetNamespace = "http://webservice.cscd.com")
                    String code
    );

    @WebMethod(action = "urn:getArticles")
    @Action(input = "urn:getArticles", output = "urn:getArticlesResponse", fault = {@FaultAction(className = CscdServiceException_Exception.class, value = "urn:getArticlesCscdServiceException")})
    @RequestWrapper(localName = "getArticles", targetNamespace = "http://webservice.cscd.com", className = "com.cscd.webservice.GetArticles")
    @ResponseWrapper(localName = "getArticlesResponse", targetNamespace = "http://webservice.cscd.com", className = "com.cscd.webservice.GetArticlesResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.cscd.com")
    public String getArticles(
            @WebParam(name = "code", targetNamespace = "http://webservice.cscd.com")
                    String code,
            @WebParam(name = "cscdIds", targetNamespace = "http://webservice.cscd.com")
                    String cscdIds
    ) throws CscdServiceException_Exception;

    @WebMethod(action = "urn:getCitedInfo")
    @Action(input = "urn:getCitedInfo", output = "urn:getCitedInfoResponse", fault = {@FaultAction(className = CscdServiceException_Exception.class, value = "urn:getCitedInfoCscdServiceException")})
    @RequestWrapper(localName = "getCitedInfo", targetNamespace = "http://webservice.cscd.com", className = "com.cscd.webservice.GetCitedInfo")
    @ResponseWrapper(localName = "getCitedInfoResponse", targetNamespace = "http://webservice.cscd.com", className = "com.cscd.webservice.GetCitedInfoResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.cscd.com")
    public String getCitedInfo(
            @WebParam(name = "code", targetNamespace = "http://webservice.cscd.com")
                    String code,
            @WebParam(name = "cscdId", targetNamespace = "http://webservice.cscd.com")
                    String cscdId
    ) throws CscdServiceException_Exception;

    @WebMethod(action = "urn:searchByExprRange")
    @Action(input = "urn:searchByExprRange", output = "urn:searchByExprRangeResponse")
    @RequestWrapper(localName = "searchByExprRange", targetNamespace = "http://webservice.cscd.com", className = "com.cscd.webservice.SearchByExprRange")
    @ResponseWrapper(localName = "searchByExprRangeResponse", targetNamespace = "http://webservice.cscd.com", className = "com.cscd.webservice.SearchByExprRangeResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.cscd.com")
    public String searchByExprRange(
            @WebParam(name = "code", targetNamespace = "http://webservice.cscd.com")
                    String code,
            @WebParam(name = "expr", targetNamespace = "http://webservice.cscd.com")
                    String expr,
            @WebParam(name = "start", targetNamespace = "http://webservice.cscd.com")
                    Integer start,
            @WebParam(name = "limit", targetNamespace = "http://webservice.cscd.com")
                    Integer limit
    );
}
